apiVersion: v1
entries:
  auto-deploy-aspnetcore:
  - apiVersion: v1
    created: 2018-05-25T14:03:01.689944662+02:00
    description: GitLab's Auto-deploy Helm Chart adapted for .NET Core
    digest: 4d5d43d95a5e074f98f262f989ef5bf78557d1d60385d70046471cd427a73916
    icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png
    name: auto-deploy-aspnetcore
    urls:
    - auto-deploy-aspnetcore-0.2.4.tgz
    version: 0.2.4
generated: 2018-05-25T14:03:01.689334013+02:00
