# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
application:
  track: stable
  tier: web
  secretName:
  secretChecksum:
gitlab:
  app:
  env:
service:
  enabled: true
  name: web
  type: ClusterIP
  url: http://my.host.com/
  additionalHosts:
  externalPort: 5000
  internalPort: 5000
ingress:
  tls:
    enabled: true
    secretName: ""
livenessProbe:
  path: "/health"
  initialDelaySeconds: 60
  timeoutSeconds: 15
readinessProbe:
  path: "/health"
  initialDelaySeconds: 60
  timeoutSeconds: 10
resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 512Mi
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1
