# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
application:
  track: stable
  tier: web
  secretName:
  secretChecksum:
  env:
gitlab:
  app:
  env:
service:
  enabled: true
  serviceName:
  name: web
  type: ClusterIP
  url: http://my.host.com/
  additionalHosts:
  externalPort: 5000
  internalPort: 5000
  annotations:
ingress:
  enabled: false
  class: "nginx"
  tls:
    enabled: true
    secretName: ""
  annotations:
livenessProbe:
  path: "/health"
  initialDelaySeconds: 10
  timeoutSeconds: 15
  periodSeconds: 10
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  path: "/ping"
  initialDelaySeconds: 10
  timeoutSeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 5
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 128Mi
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1
pod:
  annotations:
    prometheus.io/scrape: "true"
  labels:

